
                TXC "RELAYER___"
                DFB healthy
                HEX 0001            ;Level
                DFB android*16+xxtys
                HEX 00256666        ;Experience

                HEX EE

                HEX 00000000        ;Credit
                HEX 99              ;Strength
                HEX 99              ;Upper Reflex
                HEX 99              ;Lower Reflex
                HEX 99              ;Intelligence
                HEX 09              ;Electrical shielding
                HEX 07              ;Physical shielding
                HEX 03              ;Back slots
                HEX 12              ;XY

                HEX 0000            ;Damage level
                HEX 0040            ;Damage maximum
                HEX 20              ;Composition (organic)
                HEX 003909          ;Power level
                HEX 004000          ;Power maximum
                HEX CCCC            ;Power consumption

                HEX EE

                HEX 89              ; roster index (9)
                HEX 00              ; robot/cybernate link (none)

                HEX 0000            ;Power level extra digits

                HEX 0400            ;Base power consumption
                HEX 0000            ;Base shielding (e/p)

                HEX FFFFFFFF        ;e1_HEAD
                HEX FFFFFFFF        ;e2_SLOT
                HEX 42010002        ;e3_UPLFT
                HEX 42000002        ;e4_UPRGT
                HEX FFFFFFFF        ;e5_LWLFT
                HEX FFFFFFFF        ;e6_LWRGT
                HEX FFFFFFFF        ;e7_BACK1
                HEX FFFFFFFF        ;e8_BACK2
                HEX FFFFFFFF        ;e9_BACK3
                HEX FFFFFFFF        ;e10_BACK4
                HEX FFFFFFFF        ;e11_BACK5
                HEX FFFFFFFF        ;e12_BACK6
                HEX FFFFFFFF        ;e13_ARMOR
                HEX FFFFFFFF        ;e14_FEET
                HEX FFFFFFFF        ;e15_PROGRAM
                HEX FFFFFFFF        ;e16_UNUSED

                HEX 0505020A        ;Illness damager

                HEX 10              ;Base strength
                HEX 17              ;Base upper reflex
                HEX 17              ;Base lower reflex
                HEX 25              ;Base intelligence

                HEX EE
                HEX EE
                HEX 00              ;Misc
