
                TXC "BLASTER___"
                DFB healthy         ;healthy
                HEX 0001            ;Level
                DFB warrior*16+deneb
                HEX 00003999        ;Experience

                HEX EE

                HEX 00002543        ;Credit
                HEX 99              ;Strength
                HEX 99              ;Upper Reflex
                HEX 99              ;Lower Reflex
                HEX 99              ;Intelligence
                HEX 10              ;Electrical shielding
                HEX 21              ;Physical shielding
                HEX 03              ;Back slots
                HEX 25              ;XY

                HEX 0000            ;Damage level
                HEX 0075            ;Damage maximum
                HEX 45              ;Composition (organic)
                HEX 003750          ;Power level
                HEX 003750          ;Power maximum
                HEX CCCC            ;Power consumption

                HEX EE

                HEX 83              ; roster index (3)
                HEX 00              ; robot/cybernate link (none)

                HEX 0000            ;Power level extra digits

                HEX 0375            ;Base power consumption
                HEX 0102            ;Base shielding (e/p)

                HEX FFFFFFFF        ;e1_HEAD
                HEX FFFFFFFF        ;e2_SLOT
                HEX 4C0000A7        ;e3_UPLFT
                HEX 480000AD        ;e4_UPRGT
                HEX 4F070089        ;e5_LWLFT
                HEX FFFFFFFF        ;e6_LWRGT
                HEX 430200DF        ;e7_BACK1 (WHITE_SAND)
                HEX 430A00DF        ;e8_BACK2 (HEAVY_STONE)
                HEX 431200DF        ;e9_BACK3 (CHANGING_CRYSTAL)
                HEX FFFFFFFF        ;e10_BACK4
                HEX FFFFFFFF        ;e11_BACK5
                HEX FFFFFFFF        ;e12_BACK6
                HEX FFFFFFFF        ;e13_ARMOR
                HEX FFFFFFFF        ;e14_FEET
                HEX FFFFFFFF        ;e15_PROGRAM
                HEX FFFFFFFF        ;e16_UNUSED

                HEX 00000000        ;Illness damager

                HEX 21              ;Base strength
                HEX 95              ;20 ;Base upper reflex
                HEX 97              ;19 ;Base lower reflex
                HEX 06              ;Base intelligence

                HEX EE
                HEX EE
                HEX 00              ;Misc
