
                TXC "BLADE_____"
                DFB healthy
                HEX 0001            ;Level
                DFB electromedic*16+stilicx
                HEX 00006666        ;Experience

                HEX EE

                HEX 00002766        ;Credit
                HEX 09              ;Strength
                HEX 09              ;Upper Reflex
                HEX 09              ;Lower Reflex
                HEX 09              ;Intelligence
                HEX 20              ;Electrical shielding
                HEX 25              ;Physical shielding
                HEX 03              ;Back slots
                HEX 41              ;XY

                HEX 0000            ;Damage level
                HEX 0039            ;Damage maximum
                HEX 60              ;Composition (organic)
                HEX 002345          ;Power level
                HEX 002345          ;Power maximum
                HEX CCCC            ;Power consumption

                HEX EE

                HEX 80              ; roster index (0)
                HEX 00              ; robot/cybernate link (none)

                HEX 0000            ;Power level extra digits

                HEX 0390            ;Base power consumption
                HEX 0000            ;Base shielding (e/p)

                HEX FFFFFFFF        ;e1_HEAD
                HEX FFFFFFFF        ;e2_SLOT
                HEX 41000050        ;e3_UPLFT
                HEX 61010050        ;e4_UPRGT
                HEX FFFFFFFF        ;e5_LWLFT
                HEX FFFFFFFF        ;e6_LWRGT
                HEX 431A00DF        ;e7_BACK1 (PLASTEEL_CIRCUIT)
                HEX 432200DF        ;e8_BACK2 (PETRIFIED_LEAF)
                HEX 41030050        ;e9_BACK3 (ATOM_COMPRESSOR)
                HEX FFFFFFFF        ;e10_BACK4
                HEX FFFFFFFF        ;e11_BACK5
                HEX FFFFFFFF        ;e12_BACK6
                HEX FFFFFFFF        ;e13_ARMOR
                HEX FFFFFFFF        ;e14_FEET
                HEX FFFFFFFF        ;e15_PROGRAM
                HEX FFFFFFFF        ;e16_UNUSED

                HEX 00000000        ;Illness damager

                HEX 10              ;Base strength
                HEX 20              ;Base upper reflex
                HEX 21              ;Base lower reflex
                HEX 23              ;Base intelligence

                HEX EE
                HEX EE
                HEX 00              ;Misc
