
KEY_PEDESTAL
KEY_GUARD
NAJA_DOOR
SHIP_SOUND
GRAFFITI
ROTROOM
NET
QUICKD
ESTATION
VDOORS
HDOORS
CDFOUND
INFROOM
AUTOEN
NOENCNT
NOTDOOR
                CLC
                RTS

FILE_TABLE
                DB  fileAlienPics345, $0B,$00,$C0
                DB  fileAlienDesc345, $18,$00,$10

                ; TODO: remove these
                DB  fileAlienPics12,  $00,$00,$B0
                DB  fileAlienDesc12,  $17,$00,$10

                DB  fileDiagnose,     $19,$00,$0E
                DB  fileAlienId,      $1A,$00,$06

                DB  fileElevator, $1A,$08,$08
                ; TODO: trim this length
                DB  fileKeyDoor,  $1D,$00,$10
