
FILE_TABLE      DB  fileAlienPics12,  $00,$00,$B0   ; trim
                DB  fileAlienDesc12,  $0C,$00,$10   ; trim

                DB  fileControl17,    $10,$00,$10   ; trim
                DB  fileControl15,    $11,$00,$10   ; trim
                DB  fileControl13,    $10,$00,$10   ; different disk, trim

                DB  fileDiagnose,     $14,$00,$0E
                DB  fileAlienId,      $15,$00,$06
                DB  fileElevator,     $15,$08,$08
