
SHIP_SOUND
ROTATE
IN_ONE_WAY
DATACARD_COMP
WEAPON_FOUND
KILROY
IS_DOOR
NOT_DOOR
KEY_GUARD
                CLC
                RTS

FILE_TABLE
                DB  fileAlienPics12,  $00,$00,$B0
                DB  fileAlienDesc12,  $17,$00,$10

                ; TODO: remove these
                DB  fileAlienPics345, $0B,$00,$C0
                DB  fileAlienDesc345, $18,$00,$10

                DB  fileDiagnose,     $19,$00,$0E
                DB  fileAlienId,      $1A,$00,$06

                DB  fileElevator, $1A,$08,$08
                DB  fileViewport, $1B,$00,$09
                DB  fileRuuik,    $1C,$00,$0D
