BLOCK_LIST      DW  BLOCK_00
                DW  BLOCK_10
                DW  BLOCK_20
                DW  BLOCK_30
                DW  BLOCK_40
                DW  BLOCK_50
                DW  BLOCK_60
                DW  BLOCK_70
                DW  BLOCK_80
                DW  BLOCK_90
                DW  BLOCK_A0
                DW  BLOCK_B0
                DW  0
                DW  0
                DW  BLOCK_E0


BLOCK_00
                TXI "SWINGS"
                TXI "STRIKES"
                TXI "POKES"
                TXI "SCRATCHES"
                TXI "CLAWS"
                TXI "STABS"
                TXI "THRUSTS"
                TXI "HACKS"
                TXI "SLASHES"
                TXI "BITES"
                TXI "SNIPS"
                TXI "PUNCHES"
                TXI "GRABS"
                TXI "REACHES"
                TXI "KICKES"
                TXI "WHIPS"

BLOCK_10
                TXI "SWOOPS"
                TXI "SPRAYS"
                TXI "LUNGES"
                TXI "JUMPS"
                TXI "AS"
                TXI "TO"
                TXI "THE"
                TXI "HIT"
                TXI "GRENADE"
                TXI "EXPLODES"
                TXI "SONIC"
                TXI "BURNED"
                TXI "BLINDED"
                TXI "GYRO"
                TXI "TOWARD"
                TXI "ARCS"

BLOCK_20
                TXI "BOOMERANG"
                TXI "BEING"
                TXI "ANYTHING"
                TXI "CUTS"
                TXI "SCANS"
                TXI "FAILS"
                TXI "IDENTIFY"
                TXI "IDENTIFIES"
                TXI "SLICES"
                TXI "DOESN'T"
                TXI "THRASHES"
                TXI "SWIPES"
                TXI "TRANSMIT"
                TXI "TRANSMITS"
                TXI "SWING"
                TXI "CRACKS"

BLOCK_30
                TXI "AND"
                TXI "FOR"
                TXI "NOTHING"
                TXI "INFLICTS"      ;|
                TXI "CAUSES"        ;|
                TXI "CONNECTS"      ;|
                TXI "HITS"          ;|
                TXI "DAMAGE"
                TXI "IS"
                TXI "KILLED"        ;|
                TXI "DESTROYED"     ;|
                TXI "FIRE"          ;  |
                TXI "SHOOT"         ;  |
                TXI "BLAST"         ;  |
                TXI "SHOT"          ;  |
                TXI "MISSES"        ;|
                                    ;|
BLOCK_40                            ;|
                TXI "WHIZZES"       ;|
                TXI "FLIES"         ;|
                TXI "BUZZES"        ;|
                TXI "WITH"
                TXI "BUT"
                TXI "IT"
                TXI "RICOCHETS"
                TXI "PAST"
                TXI "ATTACKER"
                TXI "BRAIN"
                TXI "JAMMING"
                TXI "WAVES"
                TXI "WIDE"
                TXI "VIBRATE"
                TXI "OF"
                TXI "UNLOADS"

BLOCK_50
                TXI "SEEM"
                TXI "HAVE"
                TXI "WEAK"
                TXI "HARMLESS"
                TXI "UNIT"
                TXI "LETS LOOSE"
                TXI "THROWS"
                TXI "DISCHARGES"
                TXI "RELEASES"
                TXI "EMITS"
                TXI "SCORCHING"     ;|
                TXI "BURNING"       ;|
                TXI "SEARING"       ;|
                TXI "CRACKLING"     ;   |
                TXI "PULSATING"     ;   |
                TXI "GLOWING"       ;   |
                                    ;   |
BLOCK_60                            ;   |
                TXI "BRILLIANT"     ;   |
                TXI "BLINDING"      ;   |
                TXI "GLARING"       ;   |
                TXI "BOLT"
                TXI "FLASH"
                TXI "ENERGY"
                TXI "RUNS"
                TXI "OUT"
                TXI "BLOCKED"
                TXI "INTERCEPTED"
                TXI "WALL"
                TXI "STARTS"
                TXI "EFFECT"
                TXI "STOPS"
                TXI "ABRUPTLY"
                TXI "IN"

BLOCK_70
                TXI "WAY"
                TXI "NO"
                TXI "ONE"
                TXI "AFFECTED"
                TXI "THAT"
                TXI "EVERYBODY"
                TXI "SO"
                TXI "OFF"
                TXI "IT'S"
                TXI "RESTRAINING"
                TXI "MESSAGE"
                TXI "ABSORBED"
                TXI "BY"
                TXI "INTO"
                TXI "REMAINS"
                TXI "DODGES"        ;|
                                    ;|
BLOCK_80                            ;|
                TXI "DUCKS"         ;|
                TXI "EVADES"        ;|
                TXI "AVOIDS"        ;|
                TXI "BLOCKS"
                TXI "ATTACK"
                TXI "DAMAGED"       ;|
                TXI "INJURED"       ;|
                TXI "HARMED"        ;|
                TXI "GOES"
                TXI "ISN'T"
                TXI "QUICK"
                TXI "ENOUGH"
                TXI "THIN AIR"                  ;|
                TXI "NOBODY"                    ;|
                TXI "AN EMPTY SQUARE"       ;|
                TXI "DEFLECTED"

BLOCK_90
                TXI "BADLY"
                TXI "BLOW"
                TXI "RECEIVED"
                TXI "ANYONE"
                TXI "IGNORED"
                TXI "OBEYED"
                TXI "POWERFUL"      ;|
                TXI "DEVASTATING"   ;|
                TXI "DESTRUCTIVE"   ;|
                TXI "UNKNOWN"       ;   |
                TXI "ALIEN"         ;   |
                TXI "ROBOT"         ;   |
                TXI "EXCHANGES"
                TXI "EQUIPMENT"
                TXI "HEALS"         ;|
                TXI "REPAIRS"       ;|

BLOCK_A0
                TXI "LONGER"
                TXI "SNIFFS"
                TXI "MUSCLE"        ;|
                TXI "REFLEX"        ;|
                TXI "DIES"
                TXI "INSTANTLY"
                TXI "NOT"
                TXI "RETURNS"
                TXI "A"
                TXI "AT"
                TXI "AN"
                TXI "STRIKE"
                TXI "DETONATE"
                TXI "CRASHES"
                TXI "FLOOR"
                TXI "DOES"

BLOCK_B0
                TXI "GIVES"
                TXI "RETREAT"
                TXI "SIGNAL"
                TXI "ACTIVATE"
                TXI "ENVELOPS"
                TXI "IMMOBILIZER"
                TXI "IMMOBILIZE"
                TXI "SEND"
                TXI "SENDS"
                TXI "HAS"
                TXI "CRITICAL"
                TXI "BROKEN"
                TXI "IMMOBILE"
                TXI "RESTRAINED"
                TXI "JAMMED"
                TXI "X"             ;*


*** THESE ARE USED IN RUN RESOLVER CODE
BLOCK_E0
                TXI "GROUP"
                TXI "ALIENS"
                TXI "SUCCESSFULLY"
                TXI "ATTEMPT"
                TXI "UNSUCCESSFUL"
                TXI "RETREATED"
