
                EXP OFF

                PUT /NAJA/VARS/CONSTANTS

                ORG $0800

                PUT VARS

                PUT TABLES
                PUT UTILS
                PUT BLIT
                PUT PICT
                DS  16                  ;***
                PUT UNPACK
                PUT SHAPES
                PUT TEXT
                PUT INPUT
                PUT FONT
                PUT CURSORS

                ; TODO: move this from COMMON
                PUT FILES

                SAV COMMON
