
                EXP OFF

                PUT /NAJA/VARS/CONSTANTS

                ORG $0800

                PUT VARS

                PUT TABLES
                PUT UTILS
                PUT UNPACK
                PUT BLIT
                PUT SHAPES
                PUT PICT
                PUT TEXT
                PUT INPUT
                PUT FONT
                PUT CURSORS

                DS  \,$EE
                ERR $1A00-*

                SAV COMMON
