
                EXP OFF

                ORG $0800

                PUT VARS

                PUT TABLES
                PUT UTILS
                PUT PICT

                DS  64              ;***

                PUT SHAPE
                PUT TEXT
                PUT FONT
                PUT CURSORS

                DS  32              ;***

                PUT UNPACK

                SAV COMMON
